export const Strings = {
  truth: 'Truth',
  dare: 'Dare',
  kids: 'Kids',
  teens: 'Teens',
  adults: 'Adults',
  lets_play: "Let's Play",
  setting: 'Setting',
  rate_us: 'Rate Us',
  forfeit: 'Forfeit',
  done: 'Done',
  add_truth: 'Add Truth',
  add_dare: 'Add Dare',
  sound_on: 'Sound On',
  share: 'Share',
};
